# Generated by Django 6.0.2 on 2026-02-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='@Abumalik08', max_length=100, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], null=True, verbose_name='Класс')),
                ('letter', models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=1, null=True, verbose_name='Буква')),
                ('use_global', models.BooleanField(default=True, verbose_name='Глобальное расписание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='GlobalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Класс')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква')),
                ('day', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ')], verbose_name='День недели')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Глобальный урок',
                'verbose_name_plural': 'Глобальные уроки',
                'ordering': ['grade', 'letter', 'day', 'number'],
                'unique_together': {('grade', 'letter', 'day', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PersonalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ')], verbose_name='День недели')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_lessons', to='bot.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Личный урок',
                'verbose_name_plural': 'Личные уроки',
                'ordering': ['student', 'day', 'number'],
                'unique_together': {('student', 'day', 'number')},
            },
        ),
    ]
